<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import pandas as pd
import quandl

In [3]:
def get_tickers():
    companies=pd.read_csv('https://s3-eu-west-1.amazonaws.com/ih-materials/uploads/data-static/data/module-1/companies.csv')
    ticker_list=companies.Ticker.to_list()
    print('retrieved',str(len(ticker_list)), 'ticker symbols.')
    return ticker_list

In [4]:
def get_prices(ticker):
    print('retrieving data for', ticker)
    prices=quandl.get('WIKI/'+ticker)['Adj. Close'].reset_index()
    prices['Ticker']=ticker
    return prices

In [5]:
def acquisition():
    data=[]
    ticker_list=get_tickers()

    for ticker in ticker_list:
        prices=get_prices(ticker)
        data.append(prices)
    df=pd.concat(data,sort=True)
    return df

In [6]:
def concat_pivot(rows,data,columns='Ticker',values='Adj. Close'):
    pivot=data.pivot_table(values=values,columns=columns,index=rows)
    return pivot

In [7]:
def compute_returns(df):
    returns=df.pct_change()
    return returns

In [8]:
acquisition().pipe((concat_pivot, 'data'), rows='Date', values='Adj. Close', columns='Ticker').pipe(compute_returns)

retrieved 30 ticker symbols.
retrieving data for AAPL
retrieving data for NFLX
retrieving data for AMZN
retrieving data for MSFT
retrieving data for GOOG
retrieving data for TSLA
retrieving data for FB
retrieving data for AAP
retrieving data for DIS
retrieving data for NKE
retrieving data for UA
retrieving data for BAC
retrieving data for CCL
retrieving data for CI
retrieving data for AAL
retrieving data for LUV
retrieving data for WFC
retrieving data for WMT
retrieving data for HD
retrieving data for ORCL
retrieving data for IBM
retrieving data for NCLH
retrieving data for RCL
retrieving data for TWX
retrieving data for FOX
retrieving data for F
retrieving data for GCI
retrieving data for XOM
retrieving data for WWE
retrieving data for WM

Ticker,AAL,AAP,AAPL,AMZN,BAC,CCL,CI,DIS,F,FB,...,ORCL,RCL,TSLA,TWX,UA,WFC,WM,WMT,WWE,XOM
Date,,,,,,,,,,,,,,,,,,,,,
1962-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.013423,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.003444,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1962-01-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.003432,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-03-21,-0.022234,0.008665,-0.022655,-0.002931,-0.003440,-0.011643,0.012424,0.004637,0.010009,0.007374,...,-0.000638,-0.011933,0.019256,0.001156,0.004283,-0.002004,-0.004057,0.002615,-0.005207,0.014191
2018-03-22,-0.032908,-0.030632,-0.014159,-0.023871,-0.041418,-0.012824,-0.010236,-0.011982,-0.031532,-0.026566,...,-0.024032,-0.025857,-0.023473,-0.010809,-0.025586,-0.041248,-0.019553,-0.011794,-0.011019,-0.020522
2018-03-23,-0.024852,-0.007788,-0.023128,-0.031436,-0.045172,-0.027039,-0.008105,-0.020477,-0.017674,-0.033356,...,-0.023970,-0.026127,-0.024458,-0.017929,0.000729,-0.029507,-0.015907,-0.019738,-0.002228,-0.008299
2018-03-26,0.016663,0.035457,0.047472,0.040319,0.043538,0.021580,0.028537,0.021413,0.025568,0.004204,...,0.037732,0.024607,0.008755,0.015340,0.053936,0.025696,0.014837,0.024350,0.030151,0.015228
2018-03-27,-0.018511,0.002091,-0.025641,-0.037799,-0.030223,-0.001064,-0.018615,-0.012817,0.000000,-0.049169,...,-0.023666,-0.013509,-0.082188,0.002234,-0.009682,-0.022758,-0.009985,-0.016571,-0.019512,-0.004054

In [ ]:
compute_returns(concat_pivot(acquisition()))